### ISSUE TITLE
koppla en lättåtkomlig pdf till repot

### ISSUE THREAD

**Issue by hnrklssn** [Dsek-LTH/stadgar#1]
Till den nya hemsidan hade det varit najs om man kunde peka stadgar och reglemente mot en statisk länk som automatiskt innehöll senaste versionen av respektive styrdokument (se https://github.com/Dsek-LTH/frontend/issues/7. Jag har två tankar om hur man skulle kunna göra detta: antingen med hjälp av [releases](https://github.com/Dsek-LTH/stadgar/releases), eller med hjälp av någon CI, typ Travis, som automatiskt bygger en ny pdf på varje pull request till `master`.

**Comment by noahmay** [comment]
Jag har tänkt på att manuellt göra releases efter varje sektionsmöte är inlagt. Då skulle man kunna gå tillbaka och se hur dokumenten ser ur efter ett möte. Tycker inte man ska göra releases automatiskt i nuläget. 

Ska göra första realasen efter VTM 2019, efter det borde man bara kunna använda adressen:
/Dsek-LTH/stadgar/releases/latest/download/stadgar.pdf
för att länka till senaste releasen.

Svarar det på din fråga?

**Comment by hnrklssn** [comment]
Yes box, låter bra :)
